name: Docker testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UID: 0

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Environment info
        run: |
          docker-compose --version

      - name: Compile locales
        run: docker-compose run testing make localecompile

      - name: Build static
        run: docker-compose run testing make build-static

      - name: Test stuff
        run: |
          docker-compose run testing ./manage.py migrate
          docker-compose run testing ./manage.py makemigrations --check --dry-run

          docker-compose ps
          # Slower...
          # docker-compose run testing make coveragetest
          # Faster...
          docker-compose run testing pytest kuma/wiki/tests -x
