name: Docker testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UID: 0

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Environment info
        run: |
          docker-compose --version

      - name: Compile locales
        run: docker-compose run testing make localecompile

      - name: Build static
        run: docker-compose run testing make build-static

      - name: DB migrations
        run: |
          docker-compose run testing ./manage.py migrate
          # Essentially compares **/models.py with **/migrations/*.py and
          # makes sure the developer didn't forget to create a new migration.
          docker-compose run testing ./manage.py makemigrations --check --dry-run


      - name: Special hack
        if: ${{ github.head_ref }}
        run: |
          echo "This is a pull request"
          echo ${{ github.head_ref }}
          echo "Workflow..."
          echo ${{ github.workflow }}

      - name: Run tests
        run: |
          # TODO: Run the `make coveragetest` only if it's a pull request
          # Slower...
          docker-compose run testing make coveragetest
          # Faster...
          #docker-compose run testing make test
