name: Docker testing

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UID: 0

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Environment info
        run: |
          docker-compose --version

      - uses: satackey/action-docker-layer-caching@v0.0.8
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build docker
        run: docker-compose build

      - name: Compile locales
        run: docker-compose run testing make localecompile

      - name: Build static
        run: docker-compose run testing make build-static

      - name: DB migrations
        run: |
          docker-compose run testing ./manage.py migrate
          # Essentially compares **/models.py with **/migrations/*.py and
          # makes sure the developer didn't forget to create a new migration.
          docker-compose run testing ./manage.py makemigrations --check --dry-run

      - name: Run Python tests
        run: |
          # TODO: Run the `make coveragetest` only if it's a pull request.
          # We might be able to use something
          # like `if [ ${{ github.head_ref}} eq 'master']` but not sure.
          # Slower...
          docker-compose run testing make coveragetest
          # Faster...
          #docker-compose run testing make test

      - name: Submit code coverage
        run: |
          curl --version
          # FYI, as of April 2020, you get version 7.47.0 of curl
          # and `--retry-connrefused` was added in curl 7.52.0 :(
          bash <(curl -s --retry 3 https://codecov.io/bash)

      - name: Run JavaScript tests
        run: |
          docker-compose run testing yarn test-ci

      - name: Run localerefresh
        run: |
          docker-compose run testing make localeextract
          docker-compose run testing make localetest
          docker-compose run testing make localecompile

          cd locale
          export GIT_PAGER=cat
          git diff -G "^msgid " templates/LC_MESSAGES
